### ISSUE TITLE
Using a single socket for a reader and a writer

### ISSUE THREAD

**Issue by bltavares** [datrs/simple-message-channels#1]
Thanks for this lib :)

I'm trying use a single `async_std::net::TcpStream` to build a client, creating a reader and a writer to handle the handshakes and so on.

So far, I'm able to use a socket for sending, and one for reading, but I'm not able to use the same.
The generic types required by the struct are hard to implement and tune in.

I'm post this issue here to document the research project, as well as ask for help. Could the type constraints be refactored to accommodate this use?

<details>
<summary><strong>Sample code</strong></summary>

```rust
use async_std::net::TcpStream;
use futures::io::{AsyncRead, AsyncWrite};
use simple_message_channels::{Reader, Writer};
use std::sync::Arc;

struct Client<R, W> {
    reader: Reader<R>,
    writer: Writer<W>,
}

fn arc_based<R, W>(stream: TcpStream) -> Client<R, W>
where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Unpin,
{
    let reader = Arc::new(stream);
    let writer = reader.clone();
    let reader = Reader::new(reader);
    let writer = Writer::new(writer);
    Client { reader, writer }
}

// Based on https://book.async.rs/patterns/small-patterns.html
fn split<R, W>(stream: &TcpStream) -> Client<R, W>
where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Unpin,
{
    let (reader, writer) = &mut (&stream, &stream);
    let reader = Reader::new(reader);
    let writer = Writer::new(writer);
    Client { reader, writer }
}
```

</details>

<details>
<summary><strong>Errors</strong></summary>

```
error[E0308]: mismatched types
  --> colmeia-proto\src\lib.rs:77:22
   |
77 |     Client { reader, writer }
   |                      ^^^^^^ expected type parameter, found mutable reference
   |
   = note: expected type `simple_message_channels::writer::Writer<W>`
              found type `simple_message_channels::writer::Writer<&mut &&async_std::net::tcp::stream::TcpStream>`
   = help: type parameters must be constrained to match other types
   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters
```

```
error[E0277]: the trait bound `&&async_std::net::tcp::stream::TcpStream: futures_io::if_std::AsyncWrite` is not satisfied
  --> colmeia-proto\src\lib.rs:76:30
   |
76 |     let writer = Writer::new(writer);
   |                              ^^^^^^ the trait `futures_io::if_std::AsyncWrite` is not implemented for `&&async_std::net::tcp::stream::TcpStream`
   |
   = help: the following implementations were found:
             <&async_std::net::tcp::stream::TcpStream as futures_io::if_std::AsyncWrite>
             <async_std::net::tcp::stream::TcpStream as futures_io::if_std::AsyncWrite>
   = note: `futures_io::if_std::AsyncWrite` is implemented for `&mut &async_std::net::tcp::stream::TcpStream`, but not for `&&async_std::net::tcp::stream::TcpStream`
   = note: required because of the requirements on the impl of `futures_io::if_std::AsyncWrite` for `&mut &&async_std::net::tcp::stream::TcpStream`
   = note: required by `simple_message_channels::writer::Writer::<W>::new`
```

```
error[E0277]: the trait bound `std::sync::Arc<async_std::net::tcp::stream::TcpStream>: futures_io::if_std::AsyncRead` is not satisfied
  --> colmeia-proto\src\lib.rs:63:30
   |
63 |     let reader = Reader::new(reader);
   |                              ^^^^^^ the trait `futures_io::if_std::AsyncRead` is not implemented for `std::sync::Arc<async_std::net::tcp::stream::TcpStream>`
   |
   = note: required by `simple_message_channels::reader::Reader::<R>::new`
```

</details

**Comment by Frando** [comment]
Oh yes, that is indeed a problem at the moment. I tested with STDIO so far where this is no issue, but apparently `async_std::net::TcpStream` cannot be cloned. I tried messing with it for a couple of minutes but couldn't find a proper way. I'll think some more about it.

Maybe @yoshuawuyts has an idea how to split a `TcpStream` into an `AsyncRead` and `AsyncWrite`? Alternatively I think this could work with "proxy Read/Writes", or I might make the `Reader` and `Writer` structs work with references instead of owned values (however, at least for the Reader, I think this will get a little difficult wrt to lifetimes and pinning, not sure though).

**Comment by yoshuawuyts** [comment]
I was going to suggest the Arc-based approach here. This is code that has worked for us before (so that TcpStream can now be safely cloned):

```rust
#[derive(Clone)]
struct Stream(Arc<TcpStream>);
impl Read for Stream {
    fn poll_read(
        self: Pin<&mut Self>,
        cx: &mut Context,
        buf: &mut [u8],
    ) -> Poll<io::Result<usize>> {
        Pin::new(&mut &*self.0).poll_read(cx, buf)
    }
}
impl Write for Stream {
    fn poll_write(self: Pin<&mut Self>, cx: &mut Context, buf: &[u8]) -> Poll<io::Result<usize>> {
        Pin::new(&mut &*self.0).poll_write(cx, buf)
    }
    fn poll_flush(self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<()>> {
        Pin::new(&mut &*self.0).poll_flush(cx)
    }
    fn poll_close(self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<()>> {
        Pin::new(&mut &*self.0).poll_close(cx)
    }
}

```

__edit__: yikes, using the new GH mobile app and formatting is all over the place. Oops sorry!
__edit(frando)__: fixed formatting

**Comment by Frando** [comment]
Thanks @yoshuawuyts, I got something working with this, however I now run into problems with the Reader from this crate not being Send, thus I seem not be allowed to spawn a new thread for each incoming connection. Investigating.

**Comment by Frando** [comment]
Yay, found it!
https://github.com/datrs/simple-message-channels/commit/2f6b34f510dd4e3151d06943d8d2d9c9fc2c93a7#diff-fe8c5b0f0b5c8a2045f912ca4aaaefc7R31
Will push a TCP example now.

**Comment by Frando** [comment]
Here's the working TCP example: https://github.com/datrs/simple-message-channels/blob/master/examples/tcp.rs

I'm still not sure about best practices in rust async at all - so if things should be better differently I'm very open to changes :-)

**Comment by bltavares** [comment]
I'm able to use the new version with the cloneable socket example. I'm closing the issue.
